// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8UpHxFNh5DM0L1FdK7RgFy4gwCKKH3vo',
    appId: '1:198840577020:web:7ff409327a3920cb562079',
    messagingSenderId: '198840577020',
    projectId: 'userauthentication-507c8',
    authDomain: 'userauthentication-507c8.firebaseapp.com',
    storageBucket: 'userauthentication-507c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Zbq3GBCHPCsvQKWYQ9ee6tsnjsZpiz4',
    appId: '1:198840577020:android:dae3d62317aed54e562079',
    messagingSenderId: '198840577020',
    projectId: 'userauthentication-507c8',
    storageBucket: 'userauthentication-507c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ea4Dx9vkvrUkmb9sK9flDmYcwI1IFCw',
    appId: '1:198840577020:ios:8ad2198eaf47230e562079',
    messagingSenderId: '198840577020',
    projectId: 'userauthentication-507c8',
    storageBucket: 'userauthentication-507c8.appspot.com',
    iosBundleId: 'com.example.userAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ea4Dx9vkvrUkmb9sK9flDmYcwI1IFCw',
    appId: '1:198840577020:ios:8ad2198eaf47230e562079',
    messagingSenderId: '198840577020',
    projectId: 'userauthentication-507c8',
    storageBucket: 'userauthentication-507c8.appspot.com',
    iosBundleId: 'com.example.userAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8UpHxFNh5DM0L1FdK7RgFy4gwCKKH3vo',
    appId: '1:198840577020:web:80af1dc888d117b5562079',
    messagingSenderId: '198840577020',
    projectId: 'userauthentication-507c8',
    authDomain: 'userauthentication-507c8.firebaseapp.com',
    storageBucket: 'userauthentication-507c8.appspot.com',
  );
}
